[package]
name = "stocks"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
colored = "2.1.0"
ctrlc = "3.4.5"
num = "0.4.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_distr = "0.4.3"
serde = { version = "1.0.214", features = ["derive"] }
